; --- Laser Cut Generated by Tool ---
G21 ; mm mode
G90 ; absolute coordinates
M5  ; laser off

G0 X-2.000 Y0.000
M3 S1000
G1 X7.000 Y0.000 F50
M5

G0 X-2.000 Y50.000
M3 S1000
G1 X7.000 Y50.000 F50
M5

G0 X-2.000 Y100.000
M3 S1000
G1 X7.000 Y100.000 F50
M5

G0 X0 Y0 ; Về gốc sau khi cắt
M5
; --- END ---
